name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y empaquetar la app (sin tests)
        run: mvn clean package spring-boot:repackage -DskipTests

      - name: Analizar con Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests -Dsonar.projectKey=devsecops-jm-usach_devops_prueba_final

      - name: Ejecutar en background
        run: |
          java -Dheadless -jar target/*.jar &
          echo $! > pid.txt
    
      - name: Esperar app disponible
        run: |
            for i in {1..15}; do
              if curl -s http://localhost:8080/; then
                echo "✅ App disponible"
                exit 0
              else
                echo "⏳ Esperando la app... intento $i"
                sleep 5
              fi
            done
            echo "❌ La app no se levantó a tiempo"
            exit 1

      
